### ISSUE TITLE
dockerize test-environment

### ISSUE THREAD

**Issue by gpr7700** [Fedict/fts-test-environment#1]
Hello

Could it be possible to deploy locally the test-environment using docker images ? Would avoid each dev willing to test our own app to install minishift and all what it is required.

We could imagine having an docker image for the signature service and one for the database or having a docker image for the service that deploy everything regarding the database (scripts, ..) in a standard postgres image ? Everything could then be configured in a docker-compose file (FTS service, postgres, minio (bucket))

Regards

Gregory

**Comment by yoe** [comment]
Given that openshift/minishift requires docker containers of all the relevant applications in order to work, this should already be fairly straightforward. The Dockerfiles are committed in each repository, so you should be able to build them using a standard `docker build` in the relevant directory.

I've never worked with docker-compose (beyond running `docker-compose up` in directories prepared by others), so can't really help with creating the configuration there...

**Comment by gpr7700** [comment]
Hello Thanks for the info

We are currently working on the new e-greffe app for which the signing service is required. Can you just tell me where I can find the Dockerfiles ?

I will contact you by email to get more detailed infos.

regards

Gregory

**Comment by yoe** [comment]
Hi -- sorry, I missed your comment at first.

Each of the individual repositories comes with its own Dockerfile. For instance, the sign-validation backend has a Dockerfile at https://github.com/Fedict/fts-sign-validation/blob/master/Dockerfile

Note that these Dockerfiles assume you have run "mvn install" in the git checkout, first (i.e., they don't compile inside docker).

**Comment by gpr7700** [comment]
Hi

thanks

After some discussion with Kenneth ***@***.***)
It seems that BOSA does not have the same vision of development as we do.

Indeed, asking to be able to run the service using docker images instead of
installing minishift seems to be silly.

Our main request is just to simplify the developer's life so that he
doesn't have to depend on other external services that could hinder him in
his development

regards

Gregory

**Comment by yoe** [comment]
I think the explanation in my previous comment should be sufficient. If not, feel free to reopen this issue with a request for more information.

For now, closing.
